### ISSUE TITLE
jquey & low-dash ?

### ISSUE THREAD

**Issue by a-moses** [Pathsofdesign/boilerplates#5]
hello @Pathsofdesign  

I  want to ask if Jquery and Low dash cnds  really necessary for the Demo  project ? 

Thank you very much !

a-moses

**Comment by andrewdelprete** [comment]
Hey @a-moses, probably not haha. I need to review each boilerplate and see if I can remove. Thank you!

**Comment by a-moses** [comment]
OK !

very nice tutorial

thank you !!
